routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('command', function () {
	/* php artisan migrate */
    \Artisan::call('migrate');
    dd("Done");
});
Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('admincheck');
//DASHBOARD INDEX
Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index')->middleware('admincheck');

Route::group(['middleware' => ['role:Super Admin']], function () {

//USERS 
Route::resource('users', 'UserController')->middleware('admincheck');
//ROLES
Route::resource('role', 'RoleController')->middleware('admincheck');
//PERMISSION 
Route::resource('permission', 'PermissionController')->middleware('admincheck');
//SERVICE
Route::get('/dashboard/{id}', 'ServiceController@servicedashboard')->name('servicedashboard')->middleware('admincheck');
Route::resource('service', 'ServiceController')->middleware('admincheck');
//SYSTEM VARIABLES
Route::resource('system', 'SystemController')->middleware('admincheck');
});

//CUSTOMER
Route::resource('customer', 'CustomerController')->middleware('admincheck');

//MESSAGES
Route::get('/message', 'MessageController@index')->name('message.index')->middleware('admincheck');
Route::get('/inbox', 'MessageController@inbox')->name('inbox')->middleware('admincheck');
//SENDING MESSAGES
Route::post('/send', 'MessageController@send')->name('send')->middleware('admincheck');
Route::get('/polling', 'MessageController@polling')->name('polling')->middleware('admincheck');
Route::get('/sending', 'MessageController@sending')->name('sending')->middleware('admincheck');
Route::get('/sent', 'MessageController@sent')->name('sent')->middleware('admincheck');
Route::get('/notsent', 'MessageController@notsent')->name('notsent')->middleware('admincheck');
Route::get('/delivered', 'MessageController@delivered')->name('delivered')->middleware('admincheck');
Route::get('/undelivered', 'MessageController@undelivered')->name('undelivered')->middleware('admincheck');
//SENDING MESSAGES PER SERVICE
Route::get('/message/{id}', 'MessageController@message')->name('message')->middleware('admincheck');
//GROUP
Route::resource('group', 'GroupController')->middleware('admincheck');
//ASSINGNING CUSTOMERS TO GROUPS
Route::get('/assign/{id}', 'GroupController@assignindex')->name('assignindex')->middleware('admincheck');
Route::post('/assigned/{id}', 'GroupController@assigned')->name('assigned')->middleware('admincheck');
Route::get('/assigned_customers/{id}', 'GroupController@assignedcustomers')->name('assigncustomers')->middleware('admincheck');
//ASSINGNING GROUPS TO SERVICE
Route::get('/assigngroup/{id}', 'ServiceController@assigngroupindex')->name('assigngroupindex')->middleware('admincheck');
Route::post('/assignedgroup/{id}', 'ServiceController@assignedgroup')->name('assignedgroup')->middleware('admincheck');
Route::get('/assigned_groups/{id}', 'ServiceController@assignedgroups')->name('assigngroups')->middleware('admincheck');
//KEYWORDS
Route::resource('keyword', 'KeywordController')->middleware('admincheck');
<<<<<<< HEAD
Route::post('/keywordservicestore', 'KeywordController@keywordservicestore')->name('keywordservicestore')->middleware('admincheck');
Route::get('/keywordservice/{id}', 'KeywordController@keywordservice')->name('keywordservice')->middleware('admincheck');
Route::get('/createkeyword/{id}', 'KeywordController@createkeyword')->name('createkeyword')->middleware('admincheck');
Route::DELETE('/keyworddestroy/{id}', 'KeywordController@keyworddestroy')->name('keyworddestroy')->middleware('admincheck');

//PRICE 
Route::resource('price', 'PriceController')->middleware('admincheck');
//COMMISSION 
Route::resource('commission', 'CommissionController')->middleware('admincheck');
//TOTAL REVENUE PER DATE RANGE 
Route::get('/revenueperdate', 'DashboardController@revenueperdate')->name('revenueperdate')->middleware('admincheck');
//TOTAL REVENUE PER DATE RANGE UNDER SERVICE TYPE
Route::get('/servicerevenueperdate/{id}', 'DashboardController@servicerevenueperdate')->name('servicerevenueperdate')->middleware('admincheck');
=======
Route::get('/keywordservicecreate/{id}', 'KeywordController@createkeyword')->name('keywordservicecreate')->middleware('admincheck');
Route::post('/keywordservicestore', 'KeywordController@keywordservicestore')->name('keywordservicestore')->middleware('admincheck');
Route::get('/keywordservice/{id}', 'KeywordController@keywordservice')->name('keywordservice')->middleware('admincheck');


//PRICE 
Route::resource('price', 'PriceController')->middleware('admincheck');
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Group extends Model
{
    use SoftDeletes;
    
    /**
     * The groups has belonging to the customers.
     */
    public function customers()
    {
        return $this->belongsToMany('App\Customer','customer_group');
    }
     /**
     * The groups has belonging to the services.
     */
    public function services()
    {
        return $this->belongsToMany('App\Service','group_service');
    }
   
}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;
use DB;
use Carbon\Carbon;
use App\Customer;
use Illuminate\Http\Request;

class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groups=\App\Group::all();

        return view('group.index',compact('groups'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('group.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
            $request->validate([
                'group_name' => 'required|unique:groups,group_name',
            ]);
         
            try {
                DB::beginTransaction(); 
                $groups = new \App\Group;
                $groups->group_name= $request->input('group_name');
                $groups->description = $request->input('description');
                $groups->save();
            DB::commit();
            return redirect()->route('group.index')->with('success', 'Group Created Successfully');
        } catch (\Exception $e) {
            DB::rollback();
           
            // something went wrong
            return redirect()->back()->with('failed', $e->getMessage())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customers = DB::table('customers')->get();
        $group = DB::table('groups')->where('id','=',$id)->get()->first();
        return view('group.edit',compact('group','id','customers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $groups = \App\Group::where('id','=',$id)->get()->first();
        if($groups->group_name!=$request->input('group_name')){
        $request->validate([
        'group_name' => 'required|unique:groups,group_name',
        
         ]);
        }
        
        try{
            DB::beginTransaction();
      
            $groups->group_name = $request->input('group_name');
            $groups->description = $request->input('description');
            $groups->update();
            
        DB::commit();
        return redirect()->route('group.index')->with('success', 'Group Updated Successfully');
    } catch (\Exception $e) {
        DB::rollback();

        // something went wrong
        return redirect()->back()->with('failed',$e->getMessage())->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $group = \App\Group::where('id',$id)->delete();
        $customertogroup = \App\CustomerToGroup::where('group_id',$id)->delete();
        return redirect()->route('group.index')->with('success', 'Group Delete Successfully Wtih Their Customer Members');
    }
    public function assignindex(Request $request,$id)
    {
        //checking whether datas exist in pivot table or not

        $join = DB::table('customer_group')->get()->first();
        //retriving datas from customer table

        $customers = DB::table('customers')
        ->join('customer_group', 'customers.id', '=', 'customer_group.customer_id')
        ->where('customer_group.group_id','!=',$id)
        ->get();
        
        if($join = "null"){
        $customers = DB::table('customers')->get();
        }
        
        $group = DB::table('groups')->where('id','=',$id)->get()->first();
        return view('group.assign',compact('id','customers','group'));
   
    }
    public function assigned(Request $request,$id)
    {
        $time = Carbon::now();
        try {
            DB::beginTransaction(); 
            //getting customers id 
            $customers=$request->customerid;
            $groups=\App\Group::find($id);
           
            foreach($customers as $customer){
              $groups->customers()->attach($customer);

            }
        DB::commit();
        return redirect()->route('assignindex',$id)->with('success', 'Customers Assigned Successfully');
    } catch (\Exception $e) {
        DB::rollback();
       
        // something went wrong
        return redirect()->back()->with('failed', $e->getMessage())->withInput();
    }
     
    }
    public function assignedcustomers(Request $request,$id)
    {
        $groups = \App\Group::find($id);
        $customers=$groups->customers;
        $group = DB::table('groups')->where('id','=',$id)->get()->first();
        return view('group.assignedcustomers',compact('id','customers','group'));

    }
}

resources/views/group/assign.blade.php
@extends('layouts.vaslayout')
@section('content')
@include('group.header')
@yield('headercontent')
@include('notificationmessage.failed')
@yield('failed')
@include('notificationmessage.success')
@yield('success')
@section('headerbuttons')
@parent
	<li class="kt-menu__item  kt-menu__item--active " aria-haspopup="true"><a href="{{route('group.index')}}" class="kt-menu__link "><span class="kt-menu__link-text">Group</span></a></li>
									
				
@endsection
<<<<<<< HEAD
=======
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d

<div class="kt-portlet kt-portlet--mobile">
	<div class="kt-portlet__head">
		<div class="kt-portlet__head-label">
			<h3 class="kt-portlet__head-title">
			CUSTOMERS
			<small>LIST OF CUSTOMERS NOT ASSIGNED TO {{$group->group_name}}.</small>
			</h3>
		</div>
	</div>

	<div class="kt-portlet__body">
		<!--begin: Datatable -->
		<form method="POST" action="{{route('assigned',$group->id)}}">
			@csrf
<<<<<<< HEAD
		<table class="table table-striped- table-bordered table-hover" >
				<thead>
					<tr>
					<th>
						<label >
						<span id="lable" >
                        <input type="checkbox" onclick="selectall()" id="checkall" >
                        </span>
=======
		<table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_2">
				<thead>
					<tr>
					<th>
						<label class="kt-checkbox kt-checkbox--single kt-checkbox--solid kt-checkbox--brand">
                        <input type="checkbox"  name="select-all" id="select-all" value="" class="kt-group-checkable" >
                        <span></span>
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d
                        </label>
					</th>
					<th>CUSTOMER ID</th>
					<th>CUSTOMER PHONE</th>
					</tr>
				</thead>
			<tbody>
			@foreach($customers as $customer)
					<tr>
						<td>
<<<<<<< HEAD
						<label class="kt-checkbox kt-checkbox--brand">
							<input name="customerid[]" value="{{$customer->id}}"  type="checkbox" id="check" class="kt-group-checkable"> 
=======
						<label  class="kt-checkbox kt-checkbox--single kt-checkbox--solid kt-checkbox--brand">
							<input name="customerid[]" value="{{$customer->id}}" type="checkbox" class="kt-checkable"> 
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d
							<span></span>
                        </label>
						</td>
						<td>{{$customer->id}}</td>
						<td>{{$customer->phone}}</td>
					</tr>
            @endforeach
			</tbody>
<<<<<<< HEAD
				
		</table><div class="kt-portlet__foot">
=======
			<tfoot>
				<div class="kt-portlet__foot">
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d
					<div class="kt-form__actions">
						<div class="row">
							<div class="col-lg-6">
								<button type="submit" class="btn btn-primary">ASSIGN CUSTOMERS TO {{$group->group_name}}.</button>
							</div>
							<div class="col-lg-6 kt-align-right">
								<button type="reset" class="btn btn-danger">Delete</button>
							</div>
						</div>
					</div>
				</div>
<<<<<<< HEAD
=======
			<tfoot>
		</table>
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d
		</form>
		<!--end: Datatable -->
	</div>
</div>
<script>
table.on('change', '.kt-group-checkable', function() {
            var serv = $('#service').val();
			var set = $(this).closest('table').find('td:first-child .kt-checkable');
			var checked = $(this).is(':checked');
            console.log(set);
			$(set).each(function() {
				if (checked) {
					$(this).prop('checked', true);
					table.rows($(this).closest('tr')).select();
				}
				else {
					$(this).prop('checked', false);
					table.rows($(this).closest('tr')).deselect();
				}
			});
		});
$('.select').click(function()){

$('.kt-group-checkable').prop("checked".$(this).prop("checked")
);


});
$(document).ready(function() {
	$('.select').click(function()){

		$('.kt-group-checkable').prop("checked".$(this).prop("checked")
		);
		
	
	});
	console.log("sdfsdf");
$('.select-all').onClick(function(event)){
	if(this.checked){
		$(':checkbox').each(function(){
			this.checked=true;
		});
		else{
			$(':checkbox').each(function(){
				this.checked=false;
			});
		}
	}
});
});

</script>
@endsection

resources/views/group/create.blade.php
@extends('layouts.vaslayout')

@section('content')
@section('headerbuttons')
@parent
	<li class="kt-menu__item  kt-menu__item--active " aria-haspopup="true"><a href="{{route('group.index')}}" class="kt-menu__link "><span class="kt-menu__link-text">Group</span></a></li>
									
				
@endsection
<!-- begin:: Content Head -->
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
							<div class="kt-subheader__main">
								
								<a href="{{route('customer.index')}}" class="btn btn-label-warning btn-bold btn-sm btn-icon-h kt-margin-l-10">
									CUSTOMER INDEX
								</a>
								<div class="kt-input-icon kt-input-icon--right kt-subheader__search kt-hidden">
									<input type="text" class="form-control" placeholder="Search order..." id="generalSearch">
									<span class="kt-input-icon__icon kt-input-icon__icon--right">
										<span><i class="flaticon2-search-1"></i></span>
									</span>
								</div>
							</div>
							
						</div>

						<!-- end:: Content Head -->

<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
	<div class="row">
		<div class="col-xl-12">
			<!--begin::Portlet-->
			<div class="kt-portlet kt-portlet--head--noborder kt-portlet--height-fluid">
				<div class="kt-portlet__head">
					<div class="kt-portlet__head-label">
						<h3 class="kt-portlet__head-title">
							GROUP REGISTRATION
						</h3>
					</div>
				</div>
				<!--begin::Form-->
				<form class="kt-form kt-form--label-right" id="kt_form_1" method="POST" action="{{route('group.store')}}">

                        @csrf
					<div class="kt-portlet__body">
						
						<div class="form-group row">
						
							<div class="col-lg-6">
								<label class="">Group Name:</label>
								<div class="input-group">
								<input type="text" name="group_name" class="form-control" placeholder="Enter Group Name">
									<div class="input-group-append"><a href="#" class="btn btn-brand btn-icon"><i class="la la-users"></i></a></div>
								</div>
								<span class="form-number text-danger">{{$errors->first('group_name')}}</span>
							</div>
							
	
						</div>
						<div class="form-group row">
							<div class="col-lg-6">
								<label class="">Description:</label>
								<input type="textarea" name="description" class="form-control" placeholder="Enter description">
								<span class="form-text text-danger">{{$errors->first('description')}}</span>
							</div>
							
						</div>
						
					</div>
					<div class="kt-portlet__foot">
						<div class="kt-form__actions">
							<div class="row">
								<div class="col-lg-6">
									<button type="submit" class="btn btn-primary">Save</button>
								</div>
								<div class="col-lg-6 kt-align-right">
									<button type="reset" class="btn btn-danger">Delete</button>
								</div>
							</div>
						</div>
					</div>
				</form>
				<!--end::Form-->
			</div>
            <!--end::Portle -->
        </div>
    </div>
</div>
@endsection

resources/views/group/edit.blade.php
@extends('layouts.vaslayout')

@section('content')
@include('group.header')
@yield('headercontent')
@include('notificationmessage.failed')
@yield('failed')
@include('notificationmessage.success')
@yield('success')
@section('headerbuttons')
@parent
	<li class="kt-menu__item  kt-menu__item--active " aria-haspopup="true"><a href="{{route('group.index')}}" class="kt-menu__link "><span class="kt-menu__link-text">Group</span></a></li>
									
				
@endsection
<!-- begin:: Content Head -->


<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
	<div class="row">
		<div class="col-xl-12">
			<!--begin::Portlet-->
			<div class="kt-portlet kt-portlet--head--noborder kt-portlet--height-fluid">
				<div class="kt-portlet__head">
					<div class="kt-portlet__head-label">
						<h3 class="kt-portlet__head-title">
							EDIT GROUP 
						</h3>
					</div>
				</div>
				<!--begin::Form-->
				<form class="kt-form kt-form--label-right" id="kt_form_1" method="POST" action="{{route('group.update',$group->id)}}">
                        <input type="hidden" name="_token" value="{{csrf_token()}}">
                        <input type="hidden" name="_method" value="PUT">
					<div class="kt-portlet__body">
						<div class="form-group row">
							<div class="col-lg-6">
								<label class="">Group Name:</label>
								<div class="input-group">
								<input type="text" name="group_name" value="{{$group->group_name}}"class="form-control" placeholder="Enter Group Name">
									<div class="input-group-append"><a href="#" class="btn btn-brand btn-icon"><i class="la la-users"></i></a></div>
								</div>
								<span class="form-number text-danger">{{$errors->first('group_name')}}</span>
							</div>
							
	
						</div>
						<div class="form-group row">
							<div class="col-lg-6">
								<label class="">Description:</label>
								<input type="textarea" name="description" value="{{$group->description}}"class="form-control" placeholder="Enter description">
								<span class="form-text text-danger">{{$errors->first('description')}}</span>
							</div>
							
						</div>
						
					</div>
					<div class="kt-portlet__foot">
						<div class="kt-form__actions">
							<div class="row">
								<div class="col-lg-6">
									<button type="submit" class="btn btn-primary">Update</button>
								</div>
								<div class="col-lg-6 kt-align-right">
									<button type="reset" class="btn btn-danger">Delete</button>
								</div>
							</div>
						</div>
					</div>
				</form>
				<!--end::Form-->
			</div>
            <!--end::Portle -->
        </div>
    </div>
</div>
@endsection

resources/views/group/header.blade.php
@section('headercontent')
<!-- begin:: Content Head -->
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
	<div class="kt-subheader__main">
	
		<h3 class="kt-subheader__title">
		{{$group->group_name}} </h3>
	
		<div class="kt-input-icon kt-input-icon--right kt-subheader__search kt-hidden">
			<input type="text" class="form-control" placeholder="Search order..." id="generalSearch">
			<span class="kt-input-icon__icon kt-input-icon__icon--right">
				<span><i class="flaticon2-search-1"></i></span>
			</span>
		</div>
	</div>
	<div class="kt-subheader__toolbar">
		<div class="kt-subheader__wrapper">
			<a href="{{route('assignindex',$id)}}" class="btn kt-subheader__btn-daterange"  data-toggle="kt-tooltip" title="Assign customers to this group" data-placement="left">
				<span class="kt-subheader__btn-daterange-date" >ASSIGN</span>
				<i class="flaticon2-layers-1"></i>
            </a>
            <a href="{{route('assigncustomers',$id)}}" class="btn btn-label-warning btn-bold btn-sm btn-icon-h kt-margin-l-10"  data-toggle="kt-tooltip" title="Go To List of customers under this group" data-placement="left">
				<span class="kt-subheader__btn-daterange-date" >CUSTOMERS </span>
				<i class="flaticon2-cube-1"></i>
			</a>
		</div>
    </div>
</div>

<!-- end:: Content Head -->
@endsection

resources/views/group/index.blade.php
@extends('layouts.vaslayout')

@section('content')
@include('notificationmessage.failed')
@yield('failed')
@include('notificationmessage.success')
@yield('success')
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
							
							<div class="kt-portlet kt-portlet--mobile">
								<div class="kt-portlet__head kt-portlet__head--lg">
									<div class="kt-portlet__head-label">
										<span class="kt-portlet__head-icon">
											<i class="kt-font-brand flaticon2-line-chart"></i>
										</span>
										<h3 class="kt-portlet__head-title">
											GROUP
											<small>GROUP LIST</small>
										</h3>
									</div>
									<div class="kt-portlet__head-toolbar">
										<div class="kt-portlet__head-wrapper">
											<div class="kt-portlet__head-actions">
												<div class="dropdown dropdown-inline">
													
													<div class="dropdown-menu dropdown-menu-right">
														<ul class="kt-nav">
															<li class="kt-nav__section kt-nav__section--first">
																<span class="kt-nav__section-text">Choose an option</span>
															</li>
															<li class="kt-nav__item">
																<a href="#" class="kt-nav__link">
																	<i class="kt-nav__link-icon la la-print"></i>
																	<span class="kt-nav__link-text">Print</span>
																</a>
															</li>
															<li class="kt-nav__item">
																<a href="#" class="kt-nav__link">
																	<i class="kt-nav__link-icon la la-copy"></i>
																	<span class="kt-nav__link-text">Copy</span>
																</a>
															</li>
															<li class="kt-nav__item">
																<a href="#" class="kt-nav__link">
																	<i class="kt-nav__link-icon la la-file-excel-o"></i>
																	<span class="kt-nav__link-text">Excel</span>
																</a>
															</li>
															<li class="kt-nav__item">
																<a href="#" class="kt-nav__link">
																	<i class="kt-nav__link-icon la la-file-text-o"></i>
																	<span class="kt-nav__link-text">CSV</span>
																</a>
															</li>
															<li class="kt-nav__item">
																<a href="#" class="kt-nav__link">
																	<i class="kt-nav__link-icon la la-file-pdf-o"></i>
																	<span class="kt-nav__link-text">PDF</span>
																</a>
															</li>
														</ul>
													</div>
												</div>
												&nbsp;
												<a href="{{route('group.create')}}" class="btn btn-brand btn-elevate btn-icon-sm">
													<i class="la la-plus"></i>
													New group
												</a>
											</div>
										</div>
									</div>
								</div>
								<div class="kt-portlet__body">

									<!--begin: Search Form -->
									<div class="kt-form kt-form--label-right kt-margin-t-20 kt-margin-b-10">
										<div class="row align-items-center">
											<div class="col-xl-8 order-2 order-xl-1">
												<div class="row align-items-center">
													<div class="col-md-4 kt-margin-b-20-tablet-and-mobile">
														<div class="kt-input-icon kt-input-icon--left">
															<input type="text" class="form-control" placeholder="Search..." id="generalSearch">
															<span class="kt-input-icon__icon kt-input-icon__icon--left">
																<span><i class="la la-search"></i></span>
															</span>
														</div>
													</div>
												
												
												</div>
											</div>
											
										</div>
									</div>

									<!--end: Search Form -->
								</div>
								<div class="kt-portlet__body kt-portlet__body--fit">

									<!--begin: Datatable -->
									<table class="kt-datatable" id="html_table" width="100%">
										<thead>
											<tr>
												<th title="Field #3">GROUP ID</th>
												<th title="Field #4">GROUP NAME</th>
                                                <th title="Field #7">ACTIONS</th>
												<th title="Field #8">DESCRIPTION</th>
											</tr>
										</thead>
										<tbody>

											@foreach ($groups as $group)
											<tr>
												<td>{{ $group->id }}</td>
                                                <td>{{ $group->group_name }}</td>
                                                <td>
												<form action="{{route('group.destroy',$group->id)}}" method="post" role="form">
												<a href="{{route('assignindex',$group->id)}}" ><i class="flaticon-mark"></i></a>	&nbsp;	&nbsp; &nbsp; &nbsp; &nbsp;
												<a href="{{route('group.edit',$group->id)}}" ><i class="flaticon2-edit"></i></a>	&nbsp;	&nbsp; &nbsp;
												<input type="hidden" name="_token" value="{{csrf_token()}}">
												<input type="hidden" name="_method" value="DELETE">
												<button type="submit" class="btn btn-light btn-elevate-hover btn-icon"><i class="flaticon2-trash"></i></button>
												</form>
												</td>
												<td align="right">{{ $group->description }}</td>
											</tr>
											@endforeach
											
										</tbody>
									</table>

									<!--end: Datatable -->
								</div>
							</div>
                        </div>
@endsection