routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('command', function () {
	/* php artisan migrate */
    \Artisan::call('migrate');
    dd("Done");
});
Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('admincheck');
//DASHBOARD INDEX
Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index')->middleware('admincheck');

Route::group(['middleware' => ['role:Super Admin']], function () {

//USERS 
Route::resource('users', 'UserController')->middleware('admincheck');
//ROLES
Route::resource('role', 'RoleController')->middleware('admincheck');
//PERMISSION 
Route::resource('permission', 'PermissionController')->middleware('admincheck');
//SERVICE
Route::get('/dashboard/{id}', 'ServiceController@servicedashboard')->name('servicedashboard')->middleware('admincheck');
Route::resource('service', 'ServiceController')->middleware('admincheck');
//SYSTEM VARIABLES
Route::resource('system', 'SystemController')->middleware('admincheck');
});

//CUSTOMER
Route::resource('customer', 'CustomerController')->middleware('admincheck');

//MESSAGES
Route::get('/message', 'MessageController@index')->name('message.index')->middleware('admincheck');
Route::get('/inbox', 'MessageController@inbox')->name('inbox')->middleware('admincheck');
//SENDING MESSAGES
Route::post('/send', 'MessageController@send')->name('send')->middleware('admincheck');
Route::get('/polling', 'MessageController@polling')->name('polling')->middleware('admincheck');
Route::get('/sending', 'MessageController@sending')->name('sending')->middleware('admincheck');
Route::get('/sent', 'MessageController@sent')->name('sent')->middleware('admincheck');
Route::get('/notsent', 'MessageController@notsent')->name('notsent')->middleware('admincheck');
Route::get('/delivered', 'MessageController@delivered')->name('delivered')->middleware('admincheck');
Route::get('/undelivered', 'MessageController@undelivered')->name('undelivered')->middleware('admincheck');
//SENDING MESSAGES PER SERVICE
Route::get('/message/{id}', 'MessageController@message')->name('message')->middleware('admincheck');
//GROUP
Route::resource('group', 'GroupController')->middleware('admincheck');
//ASSINGNING CUSTOMERS TO GROUPS
Route::get('/assign/{id}', 'GroupController@assignindex')->name('assignindex')->middleware('admincheck');
Route::post('/assigned/{id}', 'GroupController@assigned')->name('assigned')->middleware('admincheck');
Route::get('/assigned_customers/{id}', 'GroupController@assignedcustomers')->name('assigncustomers')->middleware('admincheck');
//ASSINGNING GROUPS TO SERVICE
Route::get('/assigngroup/{id}', 'ServiceController@assigngroupindex')->name('assigngroupindex')->middleware('admincheck');
Route::post('/assignedgroup/{id}', 'ServiceController@assignedgroup')->name('assignedgroup')->middleware('admincheck');
Route::get('/assigned_groups/{id}', 'ServiceController@assignedgroups')->name('assigngroups')->middleware('admincheck');
//KEYWORDS
Route::resource('keyword', 'KeywordController')->middleware('admincheck');
<<<<<<< HEAD
Route::post('/keywordservicestore', 'KeywordController@keywordservicestore')->name('keywordservicestore')->middleware('admincheck');
Route::get('/keywordservice/{id}', 'KeywordController@keywordservice')->name('keywordservice')->middleware('admincheck');
Route::get('/createkeyword/{id}', 'KeywordController@createkeyword')->name('createkeyword')->middleware('admincheck');
Route::DELETE('/keyworddestroy/{id}', 'KeywordController@keyworddestroy')->name('keyworddestroy')->middleware('admincheck');

//PRICE 
Route::resource('price', 'PriceController')->middleware('admincheck');
//COMMISSION 
Route::resource('commission', 'CommissionController')->middleware('admincheck');
//TOTAL REVENUE PER DATE RANGE 
Route::get('/revenueperdate', 'DashboardController@revenueperdate')->name('revenueperdate')->middleware('admincheck');
//TOTAL REVENUE PER DATE RANGE UNDER SERVICE TYPE
Route::get('/servicerevenueperdate/{id}', 'DashboardController@servicerevenueperdate')->name('servicerevenueperdate')->middleware('admincheck');
=======
Route::get('/keywordservicecreate/{id}', 'KeywordController@createkeyword')->name('keywordservicecreate')->middleware('admincheck');
Route::post('/keywordservicestore', 'KeywordController@keywordservicestore')->name('keywordservicestore')->middleware('admincheck');
Route::get('/keywordservice/{id}', 'KeywordController@keywordservice')->name('keywordservice')->middleware('admincheck');


//PRICE 
Route::resource('price', 'PriceController')->middleware('admincheck');
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;
use DB;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles=Role::get();
        return view('role.index',compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions=Permission::get();
        return view('role.create',compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:permissions',
        ]);
        $permissions=$request->permission;
        try {
            DB::beginTransaction();
            
        $Role = Role::create(['name' => $request->name]);
        foreach($permissions as $permission){
            $Role->givePermissionTo($permission);
        }
        DB::commit();
        return redirect()->route('role.index')->with('success', 'Role Created Successfully');
    } catch (\Exception $e) {
        DB::rollback();
       
        // something went wrong
        return redirect()->back()->with('failed', $e->getMessage())->withInput();
    }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::findOrFail($id);
        $permissions = Permission::all();
        return view('role.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        dd();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/role/create.blade.php
@extends('layouts.vaslayout')
@section('content')

@include('layouts.roleandpermissionheader')
@yield('headercontent')

@include('notificationmessage.failed')
@yield('failed')
@include('notificationmessage.success')
@yield('success')
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
	<div class="row">
		<div class="col-xl-12">
			<!--begin::Portlet-->
			<div class="kt-portlet kt-portlet--head--noborder kt-portlet--height-fluid">
				<div class="kt-portlet__head">
					<div class="kt-portlet__head-label">
						<h3 class="kt-portlet__head-title">
							ROLE REGISTRATION
						</h3>
					</div>
				</div>
				<!--begin::Form-->
				<form class="kt-form kt-form--label-right" id="kt_form_1" method="POST" action="{{route('role.store')}}">

                        @csrf
					<div class="kt-portlet__body">
						
						<div class="form-group row">
							<div class="col-lg-6">
								<label class="">Role Name:</label>
								<div class="input-group">
								<input type="text" name="name" class="form-control" placeholder="Enter role name">
									<div class="input-group-append"><a href="#" class="btn btn-brand btn-icon"><i class="la la-key"></i></a></div>
								</div>
								<span class="form-number text-danger">{{$errors->first('name')}}</span>
							</div>
                        </div>
                        <div class="form-group row">
                            <label>GRANT PERMISSION :</label>
                            <div class="col-md-12">
                                <div class="row">
                                    @foreach($permissions as $permission)
                                    <div class="col-md-2">
							        	<label class="kt-checkbox kt-checkbox--brand">
							        		<input name="permission[]"value="{{$permission->name}}"type="checkbox"> {{$permission->name}}
							        		<span></span>
                                        </label>
                                    </div>
                                    @endforeach
                                </div>
                                 
                            </div>
						</div>
					</div>
					<div class="kt-portlet__foot">
						<div class="kt-form__actions">
							<div class="row">
								<div class="col-lg-6">
									<button type="submit" class="btn btn-primary">Save</button>
								</div>
								<div class="col-lg-6 kt-align-right">
									<button type="reset" class="btn btn-danger">Delete</button>
								</div>
							</div>
						</div>
					</div>
				</form>
				<!--end::Form-->
			</div>
            <!--end::Portle -->
        </div>
    </div>
</div>
@endsection

resources/views/role/edit.blade.php
@extends('layouts.vaslayout')
@section('content')

@include('layouts.roleandpermissionheader')
@yield('headercontent')

@include('notificationmessage.failed')
@yield('failed')
@include('notificationmessage.success')
@yield('success')
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
	<div class="row">
		<div class="col-xl-12">
			<!--begin::Portlet-->
			<div class="kt-portlet kt-portlet--head--noborder kt-portlet--height-fluid">
				<div class="kt-portlet__head">
					<div class="kt-portlet__head-label">
						<h3 class="kt-portlet__head-title">
							EDIT ROLE 
						</h3>
					</div>
				</div>
				<!--begin::Form-->
				<form class="kt-form kt-form--label-right" id="kt_form_1" method="POST" action="{{route('role.update')}}">

					<div class="kt-portlet__body">
						
						<div class="form-group row">
							<div class="col-lg-6">
								<label class="">Role Name:</label>
								<div class="input-group">
								<input type="text" name="name" value="{{$role->name}}" class="form-control" placeholder="Enter role name">
									<div class="input-group-append"><a href="#" class="btn btn-brand btn-icon"><i class="la la-key"></i></a></div>
								</div>
								<span class="form-number text-danger">{{$errors->first('name')}}</span>
							</div>
                        </div>
                        <div class="form-group row">
                            <label>GRANT PERMISSION :</label>
                            <div class="col-md-12">
                                <div class="row">
                                    @foreach($permissions as $permission)
                                    <div class="col-md-2">
							        	<label class="kt-checkbox kt-checkbox--brand">
							        		<input name="permission[]"value="{{$permission->name}}"type="checkbox"> {{$permission->name}}
							        		<span></span>
                                        </label>
                                    </div>
                                    @endforeach
                                </div>
                                 
                            </div>
						</div>
					</div>
					<div class="kt-portlet__foot">
						<div class="kt-form__actions">
							<div class="row">
								<div class="col-lg-6">
									<button type="submit" class="btn btn-primary">Update</button>
								</div>
								<div class="col-lg-6 kt-align-right">
									<button type="reset" class="btn btn-danger">Delete</button>
								</div>
							</div>
						</div>
					</div>
				</form>
				<!--end::Form-->
			</div>
            <!--end::Portle -->
        </div>
    </div>
</div>
@endsection

resources/views/role/index.blade.php
@extends('layouts.vaslayout')

@section('content')
@include('layouts.roleandpermissionheader')
@yield('headercontent')
@include('notificationmessage.failed')
@yield('failed')
@include('notificationmessage.success')
@yield('success')

<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
	<div class="kt-portlet kt-portlet--mobile">
		<div class="kt-portlet__head kt-portlet__head--lg">
			<div class="kt-portlet__head-label">
				<span class="kt-portlet__head-icon">
					<i class="kt-font-brand flaticon2-line-chart"></i>
				</span>
				<h3 class="kt-portlet__head-title">
					ROLES
					<small>ROLES LIST</small>
				</h3>
			</div>
			<div class="kt-portlet__head-toolbar">
				<div class="kt-portlet__head-wrapper">
					<div class="kt-portlet__head-actions">
						<div class="dropdown dropdown-inline">
							
							<div class="dropdown-menu dropdown-menu-right">
								<ul class="kt-nav">
									<li class="kt-nav__section kt-nav__section--first">
										<span class="kt-nav__section-text">Choose an option</span>
									</li>
									<li class="kt-nav__item">
										<a href="#" class="kt-nav__link">
											<i class="kt-nav__link-icon la la-print"></i>
											<span class="kt-nav__link-text">Print</span>
										</a>
									</li>
									<li class="kt-nav__item">
										<a href="#" class="kt-nav__link">
											<i class="kt-nav__link-icon la la-copy"></i>
											<span class="kt-nav__link-text">Copy</span>
										</a>
									</li>
									<li class="kt-nav__item">
										<a href="#" class="kt-nav__link">
											<i class="kt-nav__link-icon la la-file-excel-o"></i>
											<span class="kt-nav__link-text">Excel</span>
										</a>
									</li>
									<li class="kt-nav__item">
										<a href="#" class="kt-nav__link">
											<i class="kt-nav__link-icon la la-file-text-o"></i>
											<span class="kt-nav__link-text">CSV</span>
										</a>
									</li>
									<li class="kt-nav__item">
										<a href="#" class="kt-nav__link">
											<i class="kt-nav__link-icon la la-file-pdf-o"></i>
											<span class="kt-nav__link-text">PDF</span>
										</a>
									</li>
								</ul>
							</div>
						</div>
						&nbsp;
						<a href="{{route('role.create')}}" class="btn btn-brand btn-elevate btn-icon-sm">
							<i class="la la-plus"></i>
							New Role
						</a>
					</div>
				</div>
			</div>
		</div>
		<div class="kt-portlet__body">
			<!--begin: Search Form -->
		</div>
		<div class="kt-portlet__body kt-portlet__body--fit">
			<!--begin: Datatable -->
			<table class="kt-datatable" id="html_table" width="100%">
				<thead>
					<tr>
						<th title="Field #3">ROLE ID</th>
						<th title="Field #4">ROLE NAME</th>
                        <th title="Field #7">ACTIONS</th>
						<th title="Field #8">DETAIL</th>
					</tr>
				</thead>
				<tbody>
				
				@foreach($roles as $role)
					<tr>
						<td>{{$role->id}}</td>
                        <td>{{$role->name}}</td>
                        <td>

							<a href="{{route('role.edit',$role->id)}}" ><i class="flaticon2-edit"></i></a>	&nbsp;	&nbsp;
							<a href="{{route('role.destroy',$role->id)}}" ><i class="flaticon2-trash"></i></a>	&nbsp;	&nbsp;
							
						</td>
                    </tr>
                @endforeach
					
				</tbody>
			</table>
			<!--end: Datatable -->
		</div>
	</div>
</div>
@endsection