routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('command', function () {
	/* php artisan migrate */
    \Artisan::call('migrate');
    dd("Done");
});
Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('admincheck');
//DASHBOARD INDEX
Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index')->middleware('admincheck');

Route::group(['middleware' => ['role:Super Admin']], function () {

//USERS 
Route::resource('users', 'UserController')->middleware('admincheck');
//ROLES
Route::resource('role', 'RoleController')->middleware('admincheck');
//PERMISSION 
Route::resource('permission', 'PermissionController')->middleware('admincheck');
//SERVICE
Route::get('/dashboard/{id}', 'ServiceController@servicedashboard')->name('servicedashboard')->middleware('admincheck');
Route::resource('service', 'ServiceController')->middleware('admincheck');
//SYSTEM VARIABLES
Route::resource('system', 'SystemController')->middleware('admincheck');
});

//CUSTOMER
Route::resource('customer', 'CustomerController')->middleware('admincheck');

//MESSAGES
Route::get('/message', 'MessageController@index')->name('message.index')->middleware('admincheck');
Route::get('/inbox', 'MessageController@inbox')->name('inbox')->middleware('admincheck');
//SENDING MESSAGES
Route::post('/send', 'MessageController@send')->name('send')->middleware('admincheck');
Route::get('/polling', 'MessageController@polling')->name('polling')->middleware('admincheck');
Route::get('/sending', 'MessageController@sending')->name('sending')->middleware('admincheck');
Route::get('/sent', 'MessageController@sent')->name('sent')->middleware('admincheck');
Route::get('/notsent', 'MessageController@notsent')->name('notsent')->middleware('admincheck');
Route::get('/delivered', 'MessageController@delivered')->name('delivered')->middleware('admincheck');
Route::get('/undelivered', 'MessageController@undelivered')->name('undelivered')->middleware('admincheck');
//SENDING MESSAGES PER SERVICE
Route::get('/message/{id}', 'MessageController@message')->name('message')->middleware('admincheck');
//GROUP
Route::resource('group', 'GroupController')->middleware('admincheck');
//ASSINGNING CUSTOMERS TO GROUPS
Route::get('/assign/{id}', 'GroupController@assignindex')->name('assignindex')->middleware('admincheck');
Route::post('/assigned/{id}', 'GroupController@assigned')->name('assigned')->middleware('admincheck');
Route::get('/assigned_customers/{id}', 'GroupController@assignedcustomers')->name('assigncustomers')->middleware('admincheck');
//ASSINGNING GROUPS TO SERVICE
Route::get('/assigngroup/{id}', 'ServiceController@assigngroupindex')->name('assigngroupindex')->middleware('admincheck');
Route::post('/assignedgroup/{id}', 'ServiceController@assignedgroup')->name('assignedgroup')->middleware('admincheck');
Route::get('/assigned_groups/{id}', 'ServiceController@assignedgroups')->name('assigngroups')->middleware('admincheck');
//KEYWORDS
Route::resource('keyword', 'KeywordController')->middleware('admincheck');
<<<<<<< HEAD
Route::post('/keywordservicestore', 'KeywordController@keywordservicestore')->name('keywordservicestore')->middleware('admincheck');
Route::get('/keywordservice/{id}', 'KeywordController@keywordservice')->name('keywordservice')->middleware('admincheck');
Route::get('/createkeyword/{id}', 'KeywordController@createkeyword')->name('createkeyword')->middleware('admincheck');
Route::DELETE('/keyworddestroy/{id}', 'KeywordController@keyworddestroy')->name('keyworddestroy')->middleware('admincheck');

//PRICE 
Route::resource('price', 'PriceController')->middleware('admincheck');
//COMMISSION 
Route::resource('commission', 'CommissionController')->middleware('admincheck');
//TOTAL REVENUE PER DATE RANGE 
Route::get('/revenueperdate', 'DashboardController@revenueperdate')->name('revenueperdate')->middleware('admincheck');
//TOTAL REVENUE PER DATE RANGE UNDER SERVICE TYPE
Route::get('/servicerevenueperdate/{id}', 'DashboardController@servicerevenueperdate')->name('servicerevenueperdate')->middleware('admincheck');
=======
Route::get('/keywordservicecreate/{id}', 'KeywordController@createkeyword')->name('keywordservicecreate')->middleware('admincheck');
Route::post('/keywordservicestore', 'KeywordController@keywordservicestore')->name('keywordservicestore')->middleware('admincheck');
Route::get('/keywordservice/{id}', 'KeywordController@keywordservice')->name('keywordservice')->middleware('admincheck');


//PRICE 
Route::resource('price', 'PriceController')->middleware('admincheck');
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Customer extends Model
{
    use SoftDeletes;
    
    protected $dates = ['deleted_at'];
    public function groups()
    {
        return $this->belongsToMany('App\Group','customer_group');
    }
   
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;
use DB;
use Illuminate\Http\Request;
use Auth;
class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       
        $customers=\App\Customer::all();
        return view('customer.index',compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('customer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $request->validate([
            'phone' => 'required|unique:customers,phone',
            'address' => 'required',

        ]);
        $customers = new \App\Customer;
        $customers->phone= $request->input('phone');
        $customers->address = $request->input('address');
        $customers->description = $request->input('description');
        $customers->save();
        return redirect()->back()->with('message', 'Successfully Registered!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customer = DB::table('customers')->where('id',$id)->get()->first();
        return view('customer.edit',compact('customer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $customers = \App\Customer::where('id','=',$id)->get()->first();
        if($customers->phone!=$request->input('phone')){
        $request->validate([
        'phone' => 'required|unique:customers,phone',
        
         ]);
        }
        
        try{
            DB::beginTransaction();
      
            $customers->phone= $request->input('phone');
            $customers->address = $request->input('address');
            $customers->description = $request->input('description');
            $customers->update();
            
        DB::commit();
        return redirect()->route('customer.index')->with('success', 'Customer Profile Updated Successfully');
    } catch (\Exception $e) {
        DB::rollback();

        // something went wrong
        return redirect()->back()->with('failed',$e->getMessage())->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $customer = \App\Customer::where('id',$id)->delete();
        $customertogroup = \App\CustomerToGroup::where('customer_id',$id)->delete();
        return redirect()->route('customer.index')->with('success', 'Customer Delete Successfully Wtih Their Group Membership');
    }
}

resources/views/customer/create.blade.php
@extends('layouts.vaslayout')

@section('content')
<!-- begin:: Content Head -->
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
							<div class="kt-subheader__main">
								
								<a href="{{route('customer.index')}}" class="btn btn-label-warning btn-bold btn-sm btn-icon-h kt-margin-l-10">
									CUSTOMER INDEX
								</a>
								<div class="kt-input-icon kt-input-icon--right kt-subheader__search kt-hidden">
									<input type="text" class="form-control" placeholder="Search order..." id="generalSearch">
									<span class="kt-input-icon__icon kt-input-icon__icon--right">
										<span><i class="flaticon2-search-1"></i></span>
									</span>
								</div>
							</div>
							<div class="kt-subheader__toolbar">
								<div class="kt-subheader__wrapper">
									<!-- <a href="#" class="btn kt-subheader__btn-secondary">Year</a>
									<a href="#" class="btn kt-subheader__btn-daterange" id="kt_dashboard_daterangepicker" data-toggle="kt-tooltip" title="Select dashboard daterange" data-placement="left">
										<span class="kt-subheader__btn-daterange-title" id="kt_dashboard_daterangepicker_title">Today</span>&nbsp;
										<span class="kt-subheader__btn-daterange-date" id="kt_dashboard_daterangepicker_date">Aug 16</span>
										<i class="flaticon2-calendar-1"></i>
									</a> -->
									<div class="dropdown dropdown-inline" data-toggle="kt-tooltip" title="Quick actions" data-placement="left">
										<a href="#" class="btn btn-icon" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
											<!-- <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon kt-svg-icon--success kt-svg-icon--md">
												<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
													<polygon id="Shape" points="0 0 24 0 24 24 0 24" />
													<path d="M5.85714286,2 L13.7364114,2 C14.0910962,2 14.4343066,2.12568431 14.7051108,2.35473959 L19.4686994,6.3839416 C19.8056532,6.66894833 20,7.08787823 20,7.52920201 L20,20.0833333 C20,21.8738751 19.9795521,22 18.1428571,22 L5.85714286,22 C4.02044787,22 4,21.8738751 4,20.0833333 L4,3.91666667 C4,2.12612489 4.02044787,2 5.85714286,2 Z" id="Combined-Shape" fill="#000000" fill-rule="nonzero" opacity="0.3" />
													<path d="M11,14 L9,14 C8.44771525,14 8,13.5522847 8,13 C8,12.4477153 8.44771525,12 9,12 L11,12 L11,10 C11,9.44771525 11.4477153,9 12,9 C12.5522847,9 13,9.44771525 13,10 L13,12 L15,12 C15.5522847,12 16,12.4477153 16,13 C16,13.5522847 15.5522847,14 15,14 L13,14 L13,16 C13,16.5522847 12.5522847,17 12,17 C11.4477153,17 11,16.5522847 11,16 L11,14 Z" id="Combined-Shape" fill="#000000" />
												</g>
											</svg> -->

											<!--<i class="flaticon2-plus"></i>-->
										</a>
										<div class="dropdown-menu dropdown-menu-right">
											<!-- <ul class="kt-nav">
												<li class="kt-nav__section kt-nav__section--first">
													<span class="kt-nav__section-text">Add new:</span>
												</li>
												<li class="kt-nav__item">
													<a href="#" class="kt-nav__link">
														<i class="kt-nav__link-icon flaticon2-graph-1"></i>
														<span class="kt-nav__link-text">Order</span>
													</a>
												</li>
												<li class="kt-nav__item">
													<a href="#" class="kt-nav__link">
														<i class="kt-nav__link-icon flaticon2-calendar-4"></i>
														<span class="kt-nav__link-text">Event</span>
													</a>
												</li>
												<li class="kt-nav__item">
													<a href="#" class="kt-nav__link">
														<i class="kt-nav__link-icon flaticon2-layers-1"></i>
														<span class="kt-nav__link-text">Report</span>
													</a>
												</li>
												<li class="kt-nav__item">
													<a href="#" class="kt-nav__link">
														<i class="kt-nav__link-icon flaticon2-calendar-4"></i>
														<span class="kt-nav__link-text">Post</span>
													</a>
												</li>
												<li class="kt-nav__item">
													<a href="#" class="kt-nav__link">
														<i class="kt-nav__link-icon flaticon2-file-1"></i>
														<span class="kt-nav__link-text">File</span>
													</a>
												</li>
											</ul> -->
										</div>
									</div>
								</div>
							</div>
						</div>

						<!-- end:: Content Head -->

<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
	<div class="row">
		<div class="col-xl-12">
			<!--begin::Portlet-->
			<div class="kt-portlet kt-portlet--head--noborder kt-portlet--height-fluid">
				<div class="kt-portlet__head">
					<div class="kt-portlet__head-label">
						<h3 class="kt-portlet__head-title">
							CUSTOMER REGISTRATION
						</h3>
					</div>
				</div>
				<!--begin::Form-->
				<form class="kt-form kt-form--label-right" id="kt_form_1" method="POST" action="{{route('customer.store')}}">

                        @csrf
					<div class="kt-portlet__body">
						
						<div class="form-group row">
						
							<div class="col-lg-6">
								<label class="">Contact Number:</label>
								<div class="input-group">
								<input type="number" name="phone" class="form-control" placeholder="Enter contact number">
									<div class="input-group-append"><a href="#" class="btn btn-brand btn-icon"><i class="la la-phone"></i></a></div>
								</div>
								<span class="form-number text-danger">{{$errors->first('phone')}}</span>
							</div>
							<div class="col-lg-6">
								<label class="">Address:</label>
								<div class="input-group">
								<input type="text" name="address" class="form-control" placeholder="Enter address ">
									<div class="input-group-append"><a href="#" class="btn btn-brand btn-icon"><i class="la la-map-marker"></i></a></div>
								</div>
								<span class="form-number text-danger">{{$errors->first('address')}}</span>
							</div>
	
						</div>
						<div class="form-group row">
							<div class="col-lg-6">
								<label class="">Description:</label>
								<input type="textarea" name="description" class="form-control" placeholder="Enter description">
								<span class="form-text text-danger">{{$errors->first('description')}}</span>
							</div>
							
						</div>
						
					</div>
					<div class="kt-portlet__foot">
						<div class="kt-form__actions">
							<div class="row">
								<div class="col-lg-6">
									<button type="submit" class="btn btn-primary">Save</button>
								</div>
								<div class="col-lg-6 kt-align-right">
									<button type="reset" class="btn btn-danger">Delete</button>
								</div>
							</div>
						</div>
					</div>
				</form>
				<!--end::Form-->
			</div>
            <!--end::Portle -->
        </div>
    </div>
</div>
@endsection

resources/views/customer/edit.blade.php
@extends('layouts.vaslayout')

@section('content')
<!-- begin:: Content Head -->
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
							<div class="kt-subheader__main">
								
								<a href="{{route('customer.index')}}" class="btn btn-label-warning btn-bold btn-sm btn-icon-h kt-margin-l-10">
									CUSTOMER INDEX
								</a>
								<div class="kt-input-icon kt-input-icon--right kt-subheader__search kt-hidden">
									<input type="text" class="form-control" placeholder="Search order..." id="generalSearch">
									<span class="kt-input-icon__icon kt-input-icon__icon--right">
										<span><i class="flaticon2-search-1"></i></span>
									</span>
								</div>
							</div>
						</div>

                        <!-- end:: Content Head -->
@include('notificationmessage.failed')
@yield('failed')

<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
	<div class="row">
		<div class="col-xl-12">
			<!--begin::Portlet-->
			<div class="kt-portlet kt-portlet--head--noborder kt-portlet--height-fluid">
				<div class="kt-portlet__head">
					<div class="kt-portlet__head-label">
						<h3 class="kt-portlet__head-title">
							EDIT CUSTOMER 
						</h3>
					</div>
				</div>
				<!--begin::Form-->
				<form class="kt-form kt-form--label-right" id="kt_form_1" method="POST" action="{{route('customer.update',$customer->id)}}">
                        <input type="hidden" name="_token" value="{{csrf_token()}}">
                        <input type="hidden" name="_method" value="PUT">
					<div class="kt-portlet__body">
						
						<div class="form-group row">
						
							<div class="col-lg-6">
								<label class="">Contact Number:</label>
								<div class="input-group">
								<input type="number" name="phone" class="form-control" value="{{$customer->phone}}" placeholder="Enter contact number">
									<div class="input-group-append"><a href="#" class="btn btn-brand btn-icon"><i class="la la-phone"></i></a></div>
								</div>
								<span class="form-number text-danger">{{$errors->first('phone')}}</span>
							</div>
							<div class="col-lg-6">
								<label class="">Address:</label>
								<div class="input-group">
								<input type="text" name="address" value="{{$customer->address}}" class="form-control" placeholder="Enter address ">
									<div class="input-group-append"><a href="#" class="btn btn-brand btn-icon"><i class="la la-map-marker"></i></a></div>
								</div>
								<span class="form-number text-danger">{{$errors->first('address')}}</span>
							</div>
	
						</div>
						<div class="form-group row">
							<div class="col-lg-6">
								<label class="">Description:</label>
								<input type="textarea" name="description" value="{{$customer->description}}"class="form-control" placeholder="Enter description">
								<span class="form-text text-danger">{{$errors->first('description')}}</span>
							</div>
							
						</div>
						
					</div>
					<div class="kt-portlet__foot">
						<div class="kt-form__actions">
							<div class="row">
								<div class="col-lg-6">
									<button type="submit" class="btn btn-primary">Update</button>
								</div>
								<div class="col-lg-6 kt-align-right">
									<button type="reset" class="btn btn-danger">Delete</button>
								</div>
							</div>
						</div>
					</div>
				</form>
				<!--end::Form-->
			</div>
            <!--end::Portle -->
        </div>
    </div>
</div>
@endsection

resources/views/customer/index.blade.php
@extends('layouts.vaslayout')
@section('content')
@include('notificationmessage.failed')
@yield('failed')
@include('notificationmessage.success')
@yield('success')
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
							
							<div class="kt-portlet kt-portlet--mobile">
								<div class="kt-portlet__head kt-portlet__head--lg">
									<div class="kt-portlet__head-label">
										<span class="kt-portlet__head-icon">
											<i class="kt-font-brand flaticon2-line-chart"></i>
										</span>
										<h3 class="kt-portlet__head-title">
											CUSTOMERS
											<small>CUSTOMERS LIST</small>
										</h3>
									</div>
									<div class="kt-portlet__head-toolbar">
										<div class="kt-portlet__head-wrapper">
											<div class="kt-portlet__head-actions">
												<div class="dropdown dropdown-inline">
													
													<div class="dropdown-menu dropdown-menu-right">
														<ul class="kt-nav">
															<li class="kt-nav__section kt-nav__section--first">
																<span class="kt-nav__section-text">Choose an option</span>
															</li>
															<li class="kt-nav__item">
																<a href="#" class="kt-nav__link">
																	<i class="kt-nav__link-icon la la-print"></i>
																	<span class="kt-nav__link-text">Print</span>
																</a>
															</li>
															<li class="kt-nav__item">
																<a href="#" class="kt-nav__link">
																	<i class="kt-nav__link-icon la la-copy"></i>
																	<span class="kt-nav__link-text">Copy</span>
																</a>
															</li>
															<li class="kt-nav__item">
																<a href="#" class="kt-nav__link">
																	<i class="kt-nav__link-icon la la-file-excel-o"></i>
																	<span class="kt-nav__link-text">Excel</span>
																</a>
															</li>
															<li class="kt-nav__item">
																<a href="#" class="kt-nav__link">
																	<i class="kt-nav__link-icon la la-file-text-o"></i>
																	<span class="kt-nav__link-text">CSV</span>
																</a>
															</li>
															<li class="kt-nav__item">
																<a href="#" class="kt-nav__link">
																	<i class="kt-nav__link-icon la la-file-pdf-o"></i>
																	<span class="kt-nav__link-text">PDF</span>
																</a>
															</li>
														</ul>
													</div>
												</div>
												&nbsp;
												<a href="{{route('customer.create')}}" class="btn btn-brand btn-elevate btn-icon-sm">
													<i class="la la-plus"></i>
													New Customer
												</a>
											</div>
										</div>
									</div>
								</div>
								<div class="kt-portlet__body">

									<!--begin: Search Form -->
									<div class="kt-form kt-form--label-right kt-margin-t-20 kt-margin-b-10">
										<div class="row align-items-center">
											<div class="col-xl-8 order-2 order-xl-1">
												<div class="row align-items-center">
													<div class="col-md-4 kt-margin-b-20-tablet-and-mobile">
														<div class="kt-input-icon kt-input-icon--left">
															<input type="text" class="form-control" placeholder="Search..." id="generalSearch">
															<span class="kt-input-icon__icon kt-input-icon__icon--left">
																<span><i class="la la-search"></i></span>
															</span>
														</div>
													</div>
												</div>
											</div>
											
										</div>
									</div>

									<!--end: Search Form -->
								</div>
								<div class="kt-portlet__body kt-portlet__body--fit">

									<!--begin: Datatable -->
									<table class="kt-datatable" id="html_table" width="100%">
										<thead>
											<tr>
												<th title="Field #3">CUSTOMER ID</th>
												<th title="Field #4">PHONE</th>
                                                <th title="Field #6">ADDRESS</th>
                                                <th title="Field #7">ACTIONS</th>
												<th title="Field #8">DESCRIPTION</th>
											</tr>
										</thead>
										<tbody>

											@foreach ($customers as $customer)
											<tr>
												<td>{{ $customer->id }}</td>
                                                <td>{{ $customer->phone }}</td>
                                                <td>{{ $customer->address }}</td>
                                                <td>
												<form action="{{route('customer.destroy',$customer->id)}}" method="post" role="form">
												<a href="{{route('customer.edit',$customer->id)}}" ><i class="flaticon2-edit"></i></a>	&nbsp;	&nbsp; &nbsp;
												<input type="hidden" name="_token" value="{{csrf_token()}}">
												<input type="hidden" name="_method" value="DELETE">
												<button type="submit" class="btn btn-light btn-elevate-hover btn-icon"><i class="flaticon2-trash"></i></button>
												</form>
												</td>
												<td align="right">{{ $customer->description }}</td>
											</tr>
											@endforeach
											
										</tbody>
									</table>

									<!--end: Datatable -->
								</div>
							</div>
                        </div>
@endsection