routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('command', function () {
	/* php artisan migrate */
    \Artisan::call('migrate');
    dd("Done");
});
Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('admincheck');
//DASHBOARD INDEX
Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index')->middleware('admincheck');

Route::group(['middleware' => ['role:Super Admin']], function () {

//USERS 
Route::resource('users', 'UserController')->middleware('admincheck');
//ROLES
Route::resource('role', 'RoleController')->middleware('admincheck');
//PERMISSION 
Route::resource('permission', 'PermissionController')->middleware('admincheck');
//SERVICE
Route::get('/dashboard/{id}', 'ServiceController@servicedashboard')->name('servicedashboard')->middleware('admincheck');
Route::resource('service', 'ServiceController')->middleware('admincheck');
//SYSTEM VARIABLES
Route::resource('system', 'SystemController')->middleware('admincheck');
});

//CUSTOMER
Route::resource('customer', 'CustomerController')->middleware('admincheck');

//MESSAGES
Route::get('/message', 'MessageController@index')->name('message.index')->middleware('admincheck');
Route::get('/inbox', 'MessageController@inbox')->name('inbox')->middleware('admincheck');
//SENDING MESSAGES
Route::post('/send', 'MessageController@send')->name('send')->middleware('admincheck');
Route::get('/polling', 'MessageController@polling')->name('polling')->middleware('admincheck');
Route::get('/sending', 'MessageController@sending')->name('sending')->middleware('admincheck');
Route::get('/sent', 'MessageController@sent')->name('sent')->middleware('admincheck');
Route::get('/notsent', 'MessageController@notsent')->name('notsent')->middleware('admincheck');
Route::get('/delivered', 'MessageController@delivered')->name('delivered')->middleware('admincheck');
Route::get('/undelivered', 'MessageController@undelivered')->name('undelivered')->middleware('admincheck');
//SENDING MESSAGES PER SERVICE
Route::get('/message/{id}', 'MessageController@message')->name('message')->middleware('admincheck');
//GROUP
Route::resource('group', 'GroupController')->middleware('admincheck');
//ASSINGNING CUSTOMERS TO GROUPS
Route::get('/assign/{id}', 'GroupController@assignindex')->name('assignindex')->middleware('admincheck');
Route::post('/assigned/{id}', 'GroupController@assigned')->name('assigned')->middleware('admincheck');
Route::get('/assigned_customers/{id}', 'GroupController@assignedcustomers')->name('assigncustomers')->middleware('admincheck');
//ASSINGNING GROUPS TO SERVICE
Route::get('/assigngroup/{id}', 'ServiceController@assigngroupindex')->name('assigngroupindex')->middleware('admincheck');
Route::post('/assignedgroup/{id}', 'ServiceController@assignedgroup')->name('assignedgroup')->middleware('admincheck');
Route::get('/assigned_groups/{id}', 'ServiceController@assignedgroups')->name('assigngroups')->middleware('admincheck');
//KEYWORDS
Route::resource('keyword', 'KeywordController')->middleware('admincheck');
<<<<<<< HEAD
Route::post('/keywordservicestore', 'KeywordController@keywordservicestore')->name('keywordservicestore')->middleware('admincheck');
Route::get('/keywordservice/{id}', 'KeywordController@keywordservice')->name('keywordservice')->middleware('admincheck');
Route::get('/createkeyword/{id}', 'KeywordController@createkeyword')->name('createkeyword')->middleware('admincheck');
Route::DELETE('/keyworddestroy/{id}', 'KeywordController@keyworddestroy')->name('keyworddestroy')->middleware('admincheck');

//PRICE 
Route::resource('price', 'PriceController')->middleware('admincheck');
//COMMISSION 
Route::resource('commission', 'CommissionController')->middleware('admincheck');
//TOTAL REVENUE PER DATE RANGE 
Route::get('/revenueperdate', 'DashboardController@revenueperdate')->name('revenueperdate')->middleware('admincheck');
//TOTAL REVENUE PER DATE RANGE UNDER SERVICE TYPE
Route::get('/servicerevenueperdate/{id}', 'DashboardController@servicerevenueperdate')->name('servicerevenueperdate')->middleware('admincheck');
=======
Route::get('/keywordservicecreate/{id}', 'KeywordController@createkeyword')->name('keywordservicecreate')->middleware('admincheck');
Route::post('/keywordservicestore', 'KeywordController@keywordservicestore')->name('keywordservicestore')->middleware('admincheck');
Route::get('/keywordservice/{id}', 'KeywordController@keywordservice')->name('keywordservice')->middleware('admincheck');


//PRICE 
Route::resource('price', 'PriceController')->middleware('admincheck');
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d

app/Keyword.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Keyword extends Model
{
    //
}

app/Http/Controllers/KeywordController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;

class KeywordController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $keywords=\App\Keyword::all();
        return view('keyword.index',compact('keywords'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $services=\App\Service::all();
        return view('keyword.create',compact('services'));
    }
    public function createkeyword($id)
    {
<<<<<<< HEAD
        
        return view('keyword.createkeyword',compact('id'));
    }
=======
        return view('keyword.createkeyword',compact('id'));
    }

>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'keyword' => 'required|unique:keywords,keyword',
            'service' => 'required',
<<<<<<< HEAD

=======
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d
        ]);
     
        try {
            DB::beginTransaction(); 
            $keywords = new \App\Keyword;
            $keywords->keyword= $request->keyword;
            $keywords->service_id = $request->service;
            $keywords->save();
        DB::commit();
        return redirect()->route('keyword.index')->with('success', 'Keyword Created Successfully');
    } catch (\Exception $e) {
        DB::rollback();
       
        // something went wrong
        return redirect()->back()->with('failed', $e->getMessage())->withInput();
    }
    }
    public function keywordservicestore(Request $request)
    {
<<<<<<< HEAD
        $request->validate([
            'keyword' => 'required|unique:keywords,keyword',
            'service' => 'required',

        ]);
     
=======
       
        $request->validate([
            'keyword' => 'required|unique:keywords,keyword',
            'service' => 'required',
        ]);
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d
        try {
            DB::beginTransaction(); 
            $keywords = new \App\Keyword;
            $keywords->keyword= $request->keyword;
            $keywords->service_id = $request->service;
            $keywords->save();
        DB::commit();
<<<<<<< HEAD
        return redirect()->route('keywordservice',['id' =>$request->service ])->with('success', 'Keyword Created Successfully');
=======
        return redirect()->route('keywordservice',['id' => $request->service])->with('success', 'Keyword Created Successfully');
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d
    } catch (\Exception $e) {
        DB::rollback();
       
        // something went wrong
        return redirect()->back()->with('failed', $e->getMessage())->withInput();
    }
    }
    public function keywordservice(Request $request,$id)
    {
<<<<<<< HEAD
      $service = DB::table('services')->where('id','=',$id)->get()->first();
     
        $keywords = DB::table('keywords')->where('service_id','=',$id)->get();
        return view('keyword.keywordservice',compact('keywords','service','id'));
    }
=======
        $keywords = DB::table('keywords')->where('service_id','=',$id)->get();
        return view('keyword.keywordservice',compact('keywords','id'));
    }

>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $keyword=\App\Keyword::where('id',$id)->get()->first();
        $services=\App\Service::get();


        return view('keyword.edit',compact('id','keyword','services'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $keywords = \App\Keyword::where('id','=',$id)->get()->first();
        if($keywords->keyword!=$request->input('keyword')){
        $request->validate([
        'keyword' => 'required|unique:keywords,keyword',
         ]);
        }
        try{
            DB::beginTransaction();
            $keywords->keyword= $request->keyword;
            $keywords->service_id = $request->service;
            $keywords->update();
        DB::commit();
        return redirect()->route('keyword.index')->with('success', 'Keyword Updated Successfully');
    } catch (\Exception $e) {
        DB::rollback();

        // something went wrong
        return redirect()->back()->with('failed',$e->getMessage())->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
<<<<<<< HEAD
        try{
            DB::beginTransaction();
        \App\Keyword::findOrFail($id)->delete();
        
        DB::commit();
        return redirect()->route('keyword.index')->with('success', 'Keyword has Deleted Successfully!!!');
        
    } catch (\Exception $e) {
        DB::rollback();

        // something went wrong
        return redirect()->back()->with('failed',$e->getMessage())->withInput();
        }
    }
    public function keyworddestroy($id)
    {
        try{
            DB::beginTransaction();
        \App\Keyword::findOrFail($id)->delete();
        
        DB::commit();
        return redirect()->back()->with('success', 'Keyword has Deleted Successfully!!!');
        
    } catch (\Exception $e) {
        DB::rollback();

        // something went wrong
        return redirect()->back()->with('failed',$e->getMessage())->withInput();
        }
=======
        //
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d
    }
}

resources/views/keyword/create.blade.php
@extends('layouts.vaslayout')
@section('content')

<<<<<<< HEAD
@include('commission.header')
=======
@include('layouts.roleandpermissionheader')
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d
@yield('headercontent')

@include('notificationmessage.failed')
@yield('failed')
@include('notificationmessage.success')
@yield('success')
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
	<div class="row">
		<div class="col-xl-12">
			<!--begin::Portlet-->
			<div class="kt-portlet kt-portlet--head--noborder kt-portlet--height-fluid">
				<div class="kt-portlet__head">
					<div class="kt-portlet__head-label">
						<h3 class="kt-portlet__head-title">
							KEYWORD REGISTRATION
						</h3>
					</div>
				</div>
				<!--begin::Form-->
				<form class="kt-form kt-form--label-right" id="kt_form_1" method="POST" action="{{route('keyword.store')}}">

                        @csrf
					<div class="kt-portlet__body">
						
						<div class="form-group row">
							<div class="col-lg-6">
								<label class="">keyword:</label>
								<div class="input-group">
								<input type="text" name="keyword" class="form-control" placeholder="Enter role name">
									<div class="input-group-append"><a href="#" class="btn btn-brand btn-icon"><i class="la la-buysellads"></i></a></div>
								</div>
								<span class="form-number text-danger">{{$errors->first('name')}}</span>
							</div>
							<div class="col-lg-6">
								<label class="">Role:</label>
								<select name="service" class="form-control" >
									<option value="">Select Roles</option>
									@foreach($services as $service)
									<option value="{{$service->id}}">{{$service->service_name}}</option>
									@endforeach
								</select>
								<span class="form-text text-danger">{{$errors->first('service')}}</span>
							</div>
                        </div>
                       
					</div>
					<div class="kt-portlet__foot">
						<div class="kt-form__actions">
							<div class="row">
								<div class="col-lg-6">
									<button type="submit" class="btn btn-primary">Save</button>
								</div>
								<div class="col-lg-6 kt-align-right">
									<button type="reset" class="btn btn-danger">Delete</button>
								</div>
							</div>
						</div>
					</div>
				</form>
				<!--end::Form-->
			</div>
            <!--end::Portle -->
        </div>
    </div>
</div>
@endsection

resources/views/keyword/createkeyword.blade.php
@extends('layouts.vaslayout')
<<<<<<< HEAD

@section('content')
@include('notificationmessage.failed')
@yield('failed')
@include('notificationmessage.success')
@yield('success')
@section('headerbuttons')
@parent
	<li class="kt-menu__item  kt-menu__item--active " aria-haspopup="true"><a href="{{route('service.index')}}" class="kt-menu__link "><span class="kt-menu__link-text">Service</span></a></li>
@endsection
=======
@section('content')

<!-- begin:: Content Head -->
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
							<div class="kt-subheader__main">
								
								<a href="{{route('service.index')}}" class="btn btn-label-warning btn-bold btn-sm btn-icon-h kt-margin-l-10">
									SERVICE INDEX
								</a>
								<div class="kt-input-icon kt-input-icon--right kt-subheader__search kt-hidden">
									<input type="text" class="form-control" placeholder="Search order..." id="generalSearch">
									<span class="kt-input-icon__icon kt-input-icon__icon--right">
										<span><i class="flaticon2-search-1"></i></span>
									</span>
								</div>
							</div>
						</div>

						<!-- end:: Content Head -->
@include('notificationmessage.failed')
@yield('failed')
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
	<div class="row">
		<div class="col-xl-12">
			<!--begin::Portlet-->
			<div class="kt-portlet kt-portlet--head--noborder kt-portlet--height-fluid">
				<div class="kt-portlet__head">
					<div class="kt-portlet__head-label">
						<h3 class="kt-portlet__head-title">
							KEYWORD REGISTRATION
						</h3>
					</div>
				</div>
				<!--begin::Form-->
				<form class="kt-form kt-form--label-right" id="kt_form_1" method="POST" action="{{route('keywordservicestore')}}">
                        @csrf
					<div class="kt-portlet__body">
						<div class="form-group row">
							<div class="col-lg-6">
								<label class="">keyword:</label>
								<div class="input-group">
                                <input type="text" name="service" class="form-control" value="{{$id}}"placeholder="" hidden>
<<<<<<< HEAD
								<input type="text" name="keyword" class="form-control" placeholder="Enter Keyword">
=======
								<input type="text" name="keyword" class="form-control" placeholder="Enter Your key Word">
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d
									<div class="input-group-append"><a href="#" class="btn btn-brand btn-icon"><i class="la la-buysellads"></i></a></div>
								</div>
								<span class="form-number text-danger">{{$errors->first('name')}}</span>
							</div>
                        </div>
					</div>
					<div class="kt-portlet__foot">
						<div class="kt-form__actions">
							<div class="row">
								<div class="col-lg-6">
									<button type="submit" class="btn btn-primary">Save</button>
								</div>
								<div class="col-lg-6 kt-align-right">
									<button type="reset" class="btn btn-danger">Delete</button>
								</div>
							</div>
						</div>
					</div>
				</form>
				<!--end::Form-->
			</div>
            <!--end::Portle -->
        </div>
    </div>
</div>
@endsection

resources/views/keyword/edit.blade.php
@extends('layouts.vaslayout')
@section('content')

@include('layouts.roleandpermissionheader')
@yield('headercontent')

@include('notificationmessage.failed')
@yield('failed')
@include('notificationmessage.success')
@yield('success')
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
	<div class="row">
		<div class="col-xl-12">
			<!--begin::Portlet-->
			<div class="kt-portlet kt-portlet--head--noborder kt-portlet--height-fluid">
				<div class="kt-portlet__head">
					<div class="kt-portlet__head-label">
						<h3 class="kt-portlet__head-title">
							KEYWORD REGISTRATION
						</h3>
					</div>
				</div>
				<!--begin::Form-->
				<form class="kt-form kt-form--label-right" id="kt_form_1" method="POST" action="{{route('keyword.update',$id)}}">
						<input type="hidden" name="_token" value="{{csrf_token()}}">
                        <input type="hidden" name="_method" value="PUT">
					<div class="kt-portlet__body">
						
						<div class="form-group row">
							<div class="col-lg-6">
								<label class="">keyword:</label>
								<div class="input-group">
								<input type="text" name="keyword" class="form-control" value="{{$keyword->keyword}}" placeholder="Enter keyword name">
									<div class="input-group-append"><a href="#" class="btn btn-brand btn-icon"><i class="la la-buysellads"></i></a></div>
								</div>
								<span class="form-number text-danger">{{$errors->first('name')}}</span>
							</div>
							<div class="col-lg-6">
								<label class="">Role:</label>
								<select name="service" class="form-control" >
									<option value="">Select Roles</option>
									@foreach($services as $service)
									<option value="{{$service->id}}">{{$service->service_name}}</option>
									@endforeach
								</select>
								<span class="form-text text-danger">{{$errors->first('service')}}</span>
							</div>
                        </div>
                       
					</div>
					<div class="kt-portlet__foot">
						<div class="kt-form__actions">
							<div class="row">
								<div class="col-lg-6">
									<button type="submit" class="btn btn-primary">Save</button>
								</div>
								<div class="col-lg-6 kt-align-right">
									<button type="reset" class="btn btn-danger">Delete</button>
								</div>
							</div>
						</div>
					</div>
				</form>
				<!--end::Form-->
			</div>
            <!--end::Portle -->
        </div>
    </div>
</div>
@endsection

resources/views/keyword/header.blade.php
@section('headercontent')
<!-- begin:: Content Head -->
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
	<div class="kt-subheader__main">
		<a href="{{route('system.index')}}" class="btn btn-label-warning btn-bold btn-sm btn-icon-h kt-margin-l-10">
        <span> <i class="flaticon2-gear"></i></span>
            SYSTEM VARIABLE
		</a>
		<div class="kt-input-icon kt-input-icon--right kt-subheader__search kt-hidden">
			<input type="text" class="form-control" placeholder="Search order..." id="generalSearch">
			<span class="kt-input-icon__icon kt-input-icon__icon--right">
				<span><i class="flaticon2-search-1"></i></span>
			</span>
		</div>
	</div>
</div>

<!-- end:: Content Head -->
@endsection

resources/views/keyword/index.blade.php
@extends('layouts.vaslayout')
@section('content')
@include('keyword.header')
@yield('headercontent')
@include('notificationmessage.failed')
@yield('failed')
@include('notificationmessage.success')
@yield('success')

<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
	<div class="kt-portlet kt-portlet--mobile">
		<div class="kt-portlet__head kt-portlet__head--lg">
			<div class="kt-portlet__head-label">
				<span class="kt-portlet__head-icon">
					<i class="kt-font-brand flaticon2-line-chart"></i>
				</span>
				<h3 class="kt-portlet__head-title">
					KEYWORDS
					<small>LIST OF KEYWORDS</small>
				</h3>
			</div>
			<div class="kt-portlet__head-toolbar">
				<div class="kt-portlet__head-wrapper">
					<div class="kt-portlet__head-actions">
						<div class="dropdown dropdown-inline">
					
						</div>
						&nbsp;
						<a href="{{route('keyword.create')}}" class="btn btn-brand btn-elevate btn-icon-sm">
							<i class="la la-plus"></i>
							New Keyword
						</a>
					</div>
				</div>
			</div>
		</div>
		<div class="kt-portlet__body">
			<!--begin: Search Form -->
		</div>
		<div class="kt-portlet__body kt-portlet__body--fit">
			<!--begin: Datatable -->
			<table class="kt-datatable" id="html_table" width="100%">
				<thead>
					<tr>
						<th title="Field #3">KEYWORD ID</th>
						<th title="Field #4">KEYWORD</th>
                        <th title="Field #7">SERVICE NAME</th>
<<<<<<< HEAD
						<th title="Field #8">ACTION</th>
=======
						<th title="Field #8">DETAIL</th>
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d
					</tr>
				</thead>
				<tbody>
				@foreach($keywords as $keyword)
					<tr>
						<td>{{$keyword->id}}</td>
                        <td>{{$keyword->keyword}}</td>
                        <td>{{$keyword->service_id}}</td>
                        <td>
<<<<<<< HEAD
						<form action="{{route('keyword.destroy',$keyword->id)}}" method="POST">
                		      @csrf
                		    <input type="hidden" name="_token" value="{{csrf_token()}}">
                		    <input type="hidden" name="_method" value="DELETE">
                		    <button type="submit" class="btn btn-outline-danger btn-icon mg-r-5"><div><i class="flaticon2-trash"></i></div></button>
                		</form> 
=======
							<a href="{{route('keyword.edit',$keyword->id)}}" ><i class="flaticon2-edit"></i></a>	&nbsp;	&nbsp;
							<a href="{{route('keyword.destroy',$keyword->id)}}" ><i class="flaticon2-trash"></i></a>	&nbsp;	&nbsp;
							
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d
						</td>
                    </tr>
                @endforeach
					
				</tbody>
			</table>
			<!--end: Datatable -->
		</div>
	</div>
</div>
@endsection

resources/views/keyword/keywordservice.blade.php
<<<<<<< HEAD

@extends('layouts.vaslayout')
@section('content')
=======
@extends('layouts.vaslayout')
@section('content')

<!-- begin:: Content Head -->
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
							<div class="kt-subheader__main">
								
								<a href="{{route('service.index')}}" class="btn btn-label-warning btn-bold btn-sm btn-icon-h kt-margin-l-10">
									SERVICE INDEX
								</a>
								<div class="kt-input-icon kt-input-icon--right kt-subheader__search kt-hidden">
									<input type="text" class="form-control" placeholder="Search order..." id="generalSearch">
									<span class="kt-input-icon__icon kt-input-icon__icon--right">
										<span><i class="flaticon2-search-1"></i></span>
									</span>
								</div>
							</div>
						</div>

						<!-- end:: Content Head -->
@include('notificationmessage.failed')
@yield('failed')
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d
@include('notificationmessage.failed')
@yield('failed')
@include('notificationmessage.success')
@yield('success')
<<<<<<< HEAD
@section('headerbuttons')
@parent
	<li class="kt-menu__item  kt-menu__item--active " aria-haspopup="true"><a href="{{route('service.index')}}" class="kt-menu__link "><span class="kt-menu__link-text">Service</span></a></li>
@endsection
=======

>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
	<div class="kt-portlet kt-portlet--mobile">
		<div class="kt-portlet__head kt-portlet__head--lg">
			<div class="kt-portlet__head-label">
				<span class="kt-portlet__head-icon">
					<i class="kt-font-brand flaticon2-line-chart"></i>
				</span>
				<h3 class="kt-portlet__head-title">
					KEYWORDS
					<small>LIST OF KEYWORDS</small>
				</h3>
			</div>
			<div class="kt-portlet__head-toolbar">
				<div class="kt-portlet__head-wrapper">
					<div class="kt-portlet__head-actions">
						<div class="dropdown dropdown-inline">
					
						</div>
						&nbsp;
<<<<<<< HEAD
						<a href="{{route('createkeyword',$id)}}" class="btn btn-brand btn-elevate btn-icon-sm">
=======
						<a href="{{route('keywordservicecreate',$id)}}" class="btn btn-brand btn-elevate btn-icon-sm">
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d
							<i class="la la-plus"></i>
							New Keyword
						</a>
					</div>
				</div>
			</div>
		</div>
		<div class="kt-portlet__body">
			<!--begin: Search Form -->
		</div>
		<div class="kt-portlet__body kt-portlet__body--fit">
			<!--begin: Datatable -->
			<table class="kt-datatable" id="html_table" width="100%">
				<thead>
					<tr>
						<th title="Field #3">KEYWORD ID</th>
						<th title="Field #4">KEYWORD</th>
						<th title="Field #4">ACTION</th>
					</tr>
				</thead>
				<tbody>
				@foreach($keywords as $keyword)
					<tr>
						<td>{{$keyword->id}}</td>
                        <td>{{$keyword->keyword}}</td>
                        <td>
<<<<<<< HEAD
						<form action="{{route('keyworddestroy',$keyword->id)}}" method="POST">
                		      @csrf
                		    <input type="hidden" name="_token" value="{{csrf_token()}}">
                		    <input type="hidden" name="_method" value="DELETE">
                		    <button type="submit" class="btn"><div><i class="flaticon2-trash"></i></div></button>
                		</form> 
=======
							<a href="{{route('keyword.destroy',$keyword->id)}}" ><i class="flaticon2-trash"></i></a>	&nbsp;	&nbsp;
>>>>>>> d68a435fd33baac5003520e8e90b3e878bcc328d
						</td>
                    </tr>
                @endforeach
					
				</tbody>
			</table>
			<!--end: Datatable -->
		</div>
	</div>
</div>
@endsection